services:
  jenkins:
    image: rd_jenkins:0.5.2
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - .jenkins_volume:/var/jenkins_home
      - .ssh_keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - service_network
    user:
      root
    restart: always
  portainer:
    image: portainer/portainer-ce:2.27.1
    container_name: rd_portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - rd-portainer-volume:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: rd_prometheus
    ports:
      - "9090:9090"
    volumes:
      - rd-prometheus-volume:/prometheus
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - service_network
    restart: always
  grafana:
    image: grafana/grafana:11.5.2
    container_name: rd_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./configs/grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml
    env_file:
      - .env
    networks:
      - service_network
    restart: always
  vikunja:
      image: vikunja/vikunja:0.24.6
      container_name: rd_vikunja
      ports:
          - "3456:3456"
      volumes:
          - rd-vikunja-volume:/app/vikunja/files
      env_file:
          - .env
      networks:
        - service_network
      depends_on:
          postgres:
              condition: service_healthy
      restart: always
  postgres:
    image: postgres:17.5
    container_name: rd_postgres
    ports:
      - "5432:5432"
    volumes:
      - rd-postgres-volume:/var/lib/postgresql/data
      - ./postgres_init/setup_dbs.sh:/docker-entrypoint-initdb.d/setup_dbs.sh
    env_file:
      - .env
    networks:
      - service_network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER}'"]
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 6
    restart: always
  pgadmin:
    image: dpage/pgadmin4:9.5.0
    container_name: rd_pgadmin
    ports:
      - "8888:80"
    volumes:
      - rd-pgadmin-volume:/var/lib/pgadmin
    env_file:
      - .env
    networks:
      - service_network
    restart: always
networks:
  service_network:
      name: jenkins_network
volumes:
  rd-portainer-volume:
  rd-prometheus-volume:
  rd-vikunja-volume:
  rd-postgres-volume:
  rd-pgadmin-volume: