services:
  registry:
    image: registry:2
    container_name: rd_registry
    ports:
      - "5000:5000"
    volumes:
      - rd-registry-volume:/var/lib/registry:rw
    networks:
      - service_network
    restart: always
  jenkins:
    image: rd_jenkins
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - .jenkins_volume:/var/jenkins_home
      - .ssh_keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - service_network
    restart: always
  portainer:
    image: portainer/portainer-ce:latest
    container_name: rd_portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - rd-portainer-volume:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: rd_prometheus
    ports:
      - "9090:9090"
    volumes:
      - rd-prometheus-volume:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - service_network
    restart: always
  grafana:
    image: grafana/grafana
    container_name: rd_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml
    env_file:
      - .env
    networks:
      - service_network
    restart: always
networks:
  service_network:
      name: jenkins_network
volumes:
  rd-registry-volume:
  rd-portainer-volume:
  rd-prometheus-volume: