services:
  registry:
    image: registry:2.8
    container_name: rd_registry
    ports:
      - "5000:5000"
    volumes:
      - rd-registry-volume:/var/lib/registry:rw
    networks:
      - service_network
    restart: always
  jenkins:
    image: rd_jenkins:0.5.1
    build: .
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - .jenkins_volume:/var/jenkins_home
      - .ssh_keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    networks:
      - service_network
    user:
      root
    restart: always
  portainer:
    image: portainer/portainer-ce:2.27.1
    container_name: rd_portainer
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - rd-portainer-volume:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: rd_prometheus
    ports:
      - "9090:9090"
    volumes:
      - rd-prometheus-volume:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - service_network
    restart: unless-stopped
  grafana:
    image: grafana/grafana:11.5.2
    container_name: rd_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.yml:/etc/grafana/provisioning/datasources/datasource.yml
    env_file:
      - .env
    networks:
      - service_network
    restart: unless-stopped
  vikunja:
      image: vikunja/vikunja:0.24.6
      container_name: rd_vikunja
      ports:
          - "3456:3456"
      volumes:
          - rd-vikunja-volume:/app/vikunja/files
      env_file:
          - .env
      depends_on:
          mariadb:
              condition: service_healthy
      restart: unless-stopped
  mariadb:
      image: mariadb:lts
      container_name: rd_mariadb
      volumes:
        - rd-mariadb-volume:/var/lib/mysql
      env_file:
          - .env
      healthcheck:
        test: ["CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3
      restart: unless-stopped
networks:
  service_network:
      name: jenkins_network
volumes:
  rd-registry-volume:
  rd-portainer-volume:
  rd-prometheus-volume:
  rd-postgres-volume:
  rd-vikunja-volume:
  rd-mariadb-volume: