version: '3.8'
services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry-volume:/var/lib/registry:rw
    networks:
      - service_network
  jenkins:
    image: mcieciora/responsible_dugong:latest
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - .jenkins_volume:/var/jenkins_home
      - .ssh_keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env_example
    networks:
      - service_network
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
    volumes:
      - portainer-volume:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
networks:
  service_network:
      name: jenkins_network
volumes:
  registry-volume:
  portainer-volume: